### ISSUE TITLE
Error shows wrong CLI option

### ISSUE THREAD

**Issue by boris-spas** [rathrio/audrey#2]
`java.lang.Error: Provide a unique project ID with --Audrey.Project="<Project ID>"`
should be `--audrey.Project="<Project ID>"` (lower case). 
Probably want to use the ID there to be future proof.

**Comment by rathrio** [comment]
Thanks!

> Probably want to use the ID there to be future proof.

Not sure I understand this correctly. Can you clarify?

**Comment by boris-spas** [comment]
Don't just do exactly what you did in that commit, and just fix the typo, but rather use the ID of the instrument so if in the future we change the name, the option descriptions are updated automatically.

**Comment by rathrio** [comment]
@boris-spas ah got it. I assumed you were referring to the project ID.
